### PR TITLE
Feature movie info display

### PR DESCRIPTION
**Pull request by nk-mart**
Displayed Movie info:

Parse data from api call.
displayed Parse data.

### CODE REVIEW

**Comment by Lawzstopwar** [comment]
Display function operated as expected

**Review by Lawzstopwar — APPROVED** [review]

**Comment by sumbal28** [comment]
#Approved 👏

**Review by Lawzstopwar — COMMENTED** [review]
Images uploaded successfully from the trending data (movie API)

**Review by Lawzstopwar — COMMENTED** [review]
changes approved

**Comment by Lawzstopwar** [comment]
approve

**Comment by sumbal28** [comment]
Approved

**Comment by sumbal28** [comment]
Approved

**Comment by sumbal28** [comment]
Approved

**Review by Lawzstopwar — APPROVED** [review]

**Review by sumbal28 — APPROVED** [review]

**Pull request merged**
